version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-deps:
        patterns:
          - "*"
    ignore:
      # eslint-plugin-qwik requires v9
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@eslint/js"
        update-types: ["version-update:semver-major"]
